# name: Build and deploy

# on:
#   # pull_request:
#   push:
#     branches:
#       - master

# jobs:
#   # build:
#   lint:
#     runs-on: ubuntu-latest
#     strategy:
#      matrix:
#       node-version: [12.x]
#     steps:
#      - uses: action/checkout@v2
#      - uses: action/setup-node@v1
#        with:
#         node-version: ${{ matrix.node-version }}
#      - run: npm ci
#      - run: npm test

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
      name: A job to say hello
    steps:
      - name: my-step
        run: echo "Hello World!"

# on: [push]

# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#     - name: Hello world action step
#       id: hello
#       uses: actions/hello-world-javascript-action@v1.1
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"
